### ISSUE TITLE
MVP typo and possible wrong equation

### ISSUE THREAD

**Issue by Partitionfunc** [WilloughbySeago/Uni-Notes#15]
Hello, 

I am glad to see a classmate, I also graduated from theoretical physics. I was looking at the MVP notes and found some mistakes.

All page numbers refer to the page of pdf documents. 

1. On page 36, just above (7.3.5), I think you are trying to write the Laplacian operator but wrote $\varphi^2$.

2. In equation (7.3.1), can you please explain how you get the $\frac{\partial F}{\partial N} = \frac {\partial \frac{F}{N} } {\partial \frac{N}{V}}$?  Shouldn't it be $\frac{\partial F}{\partial N} = \frac {\partial \frac{F}{V} } {\partial \frac{N}{V}}$?

**Comment by WilloughbySeago** [comment]
You are definitely right about the first thing, and I think probably right about the second, it makes more sense mathematically. It's been too long since I took this course for me to say for sure that there isn't something else going on, but I've changed both and made a note of the change for the second. Thanks for pointing this out and let me know if there are any other issues

**Comment by Partitionfunc** [comment]
Thanks for replying. I still find this part hard to understand. I can't figure out why N/V is the value of $\varphi$ in equilibrium, because it looks like N/V is the number density of the total number of particles which is not the definition $\varphi$. Was David Marenduzzo teaching this course when you took it? Did he post lecture notes on Myed so we can check? When I graduated I should have saved the notes...

**Comment by WilloughbySeago** [comment]
Yes it was David Marenduzzo, I have the lecture notes but this bit isn't in them, this was taken from the lectures which didn't follow the notes that closely. The notes do mention that for an ideal gas the natural order parameter is the local density, which would be proportional to the number density.

Now that I think about it I'm not even sure that $\varphi = N/V$ makes sense dimensionally, $\varphi$ should be dimensionless. I think at some point we started to ignore the $\rho_{\mathrm{W}} + \rho_{\mathrm{O}}$ denominator for $\varphi$ because it's constant if we assume everything is incompressible. Then we have $\varphi = \rho_{\mathrm{W}} - \rho_{\mathrm{O}} = N_{\mathrm{W}}m_{\mathrm{W}}/V - N_{\mathrm{O}}m_{\mathrm{O}}/V$ where $N_i$ is the number of molecules of $i$ and $m_i$ is the mass of a single molecule of $i$. Still the dimensoins don't check out, since then $\varphi$ should be a mass density, not a number density, unless $\rho_i$ is a number density to begin with, it isn't clear. If we assume that $\rho_i$ is a number density then we have $\varphi = (N_{\mathrm{W}} - N_{\mathrm{O}})/V$, which at least has the right dimensions and is correct if $N = N_{\mathrm{W}} - N_{\mathrm{O}}$ at equilibrium?
